### ISSUE TITLE
No download URL when trying to install within foundry

### ISSUE THREAD

**Issue by CydGoblin** [jessev14/resource-icons#1]
When I try to install from within foundry I get the warning that there's No download URL

**Comment by jessev14** [comment]
If you're on core v0.8.6, I haven't published a release for that version yet. Will publish the release later tonight.

**Comment by CydGoblin** [comment]
I see, thanks!

**Comment by jessev14** [comment]
New version published. I downloaded through Foundry 0.8.6 without issue.
