### ISSUE TITLE
[Feature Request] Ability to save defaults for tokens

### ISSUE THREAD

**Issue by dodgepong** [jessev14/resource-icons#10]
It would be great to be able to set defaults on tokens, possibly even different defaults for each actor type, so that we don't have to manually add icons to each token as we drag it on the field. This feature is available on Bar Brawl and I feel as though it would fit in just as well in this module.

If this is already possible, I'd love to know where I'm looking wrong!

**Comment by jessev14** [comment]
If you set up the resource icon data on an actor's prototype token, does it carry over to the token when you drag from the sidebar?

**Comment by dodgepong** [comment]
It should, but I want all actors of that actor type to all have the same resource icon setup, even when I create a brand new actor.

**Comment by jessev14** [comment]
I was in the middle of rewriting the package for v10, but decided to make it available for v9. I implemented this feature into version 2.1.0 of the module, but users updating from version 1.x.x to 2.x.x will have to re-input their resource icon data.
