### ISSUE TITLE
Conflict with Bar Brawl

### ISSUE THREAD

**Issue by Lock2022** [jessev14/resource-icons#11]
Hello thank you for this most practical module.

I allow myself to report a problem of conflict with the Bar Brawl module, when this one is activated, it is impossible to go from the resource options token icons, the selection button is not even displayed, yet the modules remain active since my icon is still displayed, I just can't modify it.

for the moment I disable bar brawl when I have to make changes, I use Resources Icons to display the LVL of my characters so nothing really advanced.

I use the Dungeon World system maybe that will help.

Thanks !
![screen](https://user-images.githubusercontent.com/85477911/179691946-257560dc-154c-4359-8758-6ff9c9d086ff.PNG)

**Comment by jessev14** [comment]
you should open an issue on bar brawl. the way they add their html pretty much destroys any html elements other modules put into this tab.
