### ISSUE TITLE
What cause that annoying error ? 

### ISSUE THREAD

**Issue by Steelskinz** [jessev14/resource-icons#13]
I did a find the culprit and it seems that Resources Icon is the one doing it.
Steps : 
Just adding a npc actor that the player don't own, like a monster or anything else. 
Effects : 
Nothing, really, except a red message that triggers on top, quite annoying. 
![image](https://user-images.githubusercontent.com/93941729/181406561-2c889188-d97c-4049-8e14-1172fe50520c.png)

**Comment by jessev14** [comment]
just adding a npc actor to what?

**Comment by Steelskinz** [comment]
To a scene, no matter wich one I get that error.

**Comment by jessev14** [comment]
can you make sure you're on version 2.1.1 of the module, and that no other modules are enabled. I'm not able to reproduce this error.

**Comment by Steelskinz** [comment]
Oh. It ... stopped doing it. That's weird. it was doing this even when I was using Find the Culprit and now it's gone, oh well, my bad sorry for the disturbance.
