### ISSUE TITLE
resources can not be edited anymore

### ISSUE THREAD

**Issue by patrickmohrmann** [jessev14/resource-icons#14]
![image](https://user-images.githubusercontent.com/76265425/181466872-78636046-e4b4-4d60-b629-f4724f5eb35d.png)

I miss the configuration possibility of the resource icons after the update

**Comment by jessev14** [comment]
It's caused by Bar Brawl. I'll have to look into it later.

**Comment by jessev14** [comment]
fixed in version 2.1.2

**Comment by patrickmohrmann** [comment]
thanks, great!
