### ISSUE TITLE
[SWADE BUG] Benny don't update

### ISSUE THREAD

**Issue by brunocalado** [jessev14/resource-icons#15]
Hi! This is a great module! Tks!!!

Can fix this? Tks

![image](https://user-images.githubusercontent.com/4999783/181925448-55d20b65-a0c6-493f-baa2-2ccf7949e5aa.png)

**Comment by jessev14** [comment]
can't seem to reproduce this. I would check to see if the problem happens if you only have resource icons enabled and everything is updated.

**Comment by brunocalado** [comment]
It's working now.
