### ISSUE TITLE
Feature Request: Update module to V10

### ISSUE THREAD

**Issue by Havoclivekiller** [jessev14/resource-icons#18]
Module isn't working for V10. For example, it crashes the token configuration and you can't close it. Nor there is a way to change the resource icons in the new V10 token config dialog.

**Comment by jessev14** [comment]
module manifest and foundry module site both state this module is only compatible with V9.

**Comment by jessev14** [comment]
I see that this is a feature request not a bug report.

I unfortunately do not have the free time to develop for Foundry outside of my paid commissions. If you would like to discuss funding this module, you can reach out to me on Discord `enso#0361`.
