### ISSUE TITLE
Request: Change the way scaling works for icons on larger tokens, or at least let users configure it

### ISSUE THREAD

**Issue by EsotericOdyssey** [jessev14/resource-icons#5]
Resource icons on tokens that are 2x2 spaces on the canvas look twice as big, which doesn't look great, visually.

**Comment by jessev14** [comment]
![image](https://user-images.githubusercontent.com/68755874/130519620-f7516f35-af29-48eb-a320-161855d6f7b8.png)
Does this look better?

**Comment by EsotericOdyssey** [comment]
quite a bit better, but would it be possible to have the icons closer together on the bigger one? if not, it's still an improvement

**Comment by jessev14** [comment]
for icons on the top/bottom of the token, would it be preferable for the icons to be left or right aligned?

**Comment by EsotericOdyssey** [comment]
honestly, I personally would prefer they be centered, both on large tokens and on normal tokens, but idk how other people feel about that

**Comment by jessev14** [comment]
centered is probably better, actually. I'll do that. the current behavior will remain the default, but you can disable icon scaling in a new module setting.

**Comment by EsotericOdyssey** [comment]
fantastic, tyvm

**Comment by jessev14** [comment]
you can get the new version by updating the module in foundry. let me know if any changes should be made
