### ISSUE TITLE
Feature Request: Hide icon if value is 0

### ISSUE THREAD

**Issue by dodgepong** [jessev14/resource-icons#8]
This module is great, but I would love it if I were able to hide icons if the associated resource was 0.

In LANCER, mechs can have Overshield and Burn applied to them. They can technically have infinite Overshield or Burn, and as such, they aren't suited for a regular bars like HP. Showing the current amount of Overshield or Burn seems like a perfect application of this module, but I don't want the icons to be visible if the mech has 0 Overshield or 0 Burn.

Would it be possible to add an option such that the icon is not rendered when the associated value is 0?

**Comment by jessev14** [comment]
easy enough. check for the new module setting in version 1.4.0

**Comment by dodgepong** [comment]
Thanks so much for implementing this so fast, this is great!

I found another bug while playing around with it more unrelated to this change, so I'll report it in another issue.

**Comment by jessev14** [comment]
I missed something that caused 0s to show when the icons are first drawn. fixed in 1.4.2
